#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobile.Resource", IsApplication=true)]

namespace Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int LoaderAnimation = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Button_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int frame001 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int frame002 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int frame003 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int frame004 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int frame005 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int frame006 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int frame007 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int frame008 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int frame009 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int frame010 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int frame011 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int frame012 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int frame013 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int frame014 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int frame015 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int frame016 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int frame017 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int frame018 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int frame019 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int frame020 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int frame021 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int frame022 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int headerImage = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Avatar = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int Button_menu = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Label = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int LabelMarshryt = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int LabelPO = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int ListViewMarsh = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int ListViewPO = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int LogoLabel = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int MapView = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int WebViewContainer = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int actionbar = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int scrollView = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int drawer_header = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int token = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
